export { default as Header } from './header';
export { default as Slider } from './homeSlider';
export { default as TabSlider } from './tabSlider';
export { default as Footer } from "./footer";
export { default as Cards } from "./serviceCard";
export { default as DescColumn } from "./aboutColumn";
export { default as TabContent } from "../components/imageColumn";
export { default as Announcements } from "../components/announceModel";
export { default as FloatingButton } from "../components/FloatingButton";